### ISSUE TITLE
Finish 0-30 Tutorial Content

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#105]
There is now a skeleton of the 0-30 tutorial in the files `z230-pt1.md` and `z230-pt2.md`.

There is still missing content in here, though, and someone needs to fill in the blanks.

That is currently missing includes:

- [x] Numpy coverage (Should this be here?)
- [x] Pandas coverage (Should this be here?)
- [x] Matplotlib + Cartopy  (Should this be here?)
- [ ] GitHub (last steps should be push up to GitHub?)
- [ ] Git conflicts, reverting git commits, etc.
- [x] Jupyter Notebooks & Lab
- [x] netCDF4-python?

**Comment by kmpaul** [comment]
Also need to generate (maybe) slides for "static" material presented during the tutorial.

**Comment by kmpaul** [comment]
Decision:  Using Jupyter Notebooks, we will cover Numpy, netcdf4, Pandas, Matplotlib+Cartopy on Day 2 (not as part of the 0-30 content)

**Comment by jukent** [comment]
Git conflicts:

Have them create branches of their work - usually copy paste file, but best practice for entertain 2 different train of thoughts is a separate branch - do old US way and new US way as 2 different wind chill formulae to motivate this.  Trying to emulate this can make it seem simpler than it is, maybe this is too advanced for day 1? Just show simple example, or link them to a better resource.

Community models are a great use case for branches and forks. Need to understand branches to contribute to CESM or other community models.

**Comment by jukent** [comment]
Let people follow curiculae https://github.com/NCAR/ncar-python-tutorial/blob/master/curricula/z230-pt1.md so that they can reference if if they get stumbled on one step. Maybe make an image  of code blocks so that people can't copy paste but can look at their leisure (and KEEP UP), maybe these images also go on powerpoint slides.

Reinforce idea of not mixing tabs and spaces!

**Comment by jukent** [comment]
Maybe name directory, spring2020tutorial instead of mysci

**Comment by jukent** [comment]
Maybe we want to show open and close file before using 'with' context manager.

**Comment by jukent** [comment]
Have them look at the header at some point

**Comment by jukent** [comment]
step 39, windchill = formula, return windchill. Separation of concerns (compute and return on separate lines to reduce confusion)

**Comment by jukent** [comment]
Suggestion for red, green, yellow post it notes to indicate needing help, being ready to move on, still working.

**Comment by jukent** [comment]
Make sure computation functions are written in a way that is easy to read (assign constants to variable before doing arithmetic on them, for ex)

**Comment by jukent** [comment]
Are pycache and gitignore high priority information?

**Comment by jukent** [comment]
Need examples on usefulness of __init__.py
