### ISSUE TITLE
Announcement Update for Spring 2020 Tutorial

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#108]
- [x] We need to announce the Spring 2020 Tutorial again.

- [x] We need to contact registered participants to get confirmation of their registration.

**Comment by jukent** [comment]
Include coronavirus contingency in email,

wait on this for one week because a lot can change with the health situation.

**Comment by kmpaul** [comment]
Yes.  Let's not pull the trigger on this too soon.  A lot can happen in a week.  And we will take our cue from UCAR leadership.
