### ISSUE TITLE
Grammar changes

### ISSUE THREAD

**Issue by sherimickelson** [NCAR/ncar-python-tutorial#120]
On the landing page:
"or you are tired of tutorials **the** leap into advanced third-party packages"
Should "the" be "that"? Or something else?

**Comment by sherimickelson** [comment]
Under the "Why Python?" section under "Objected Oriented languages":
1. Should it be Object not Objected?
2.  " For every custom datatypes".  Should "datatypes" be plural?

**Comment by mnlevy1981** [comment]
@sherimickelson -- I had moved the previous version of this issue to https://github.com/NCAR/python-tutorial/issues/33 (this is the old repo for the python tutorial)

**Comment by sherimickelson** [comment]
Ugh ... sorry I had too many windows open to notice.  I will close this issue.
