### ISSUE TITLE
Short Tutorial Seminar Series

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#121]
It's been proposed that we break up our tutorials into smaller chunks that are two-hour long segments.  Can we develop a curriculum of "seminars" that gets people to the "I'm ready for a hackathon!" stage.

**Comment by kmpaul** [comment]
See this doc:  https://hackmd.io/EobPwspVRZGl3f3bgPFH1g

**Comment by kmpaul** [comment]
I've started a Google Doc to flesh out the seminar series for the first 3-6 months:

https://docs.google.com/document/d/1sEYXyT7SMbwJdgY-poGf--tYkIBn9zN-srnaLFxLa2o/edit#

**Comment by jukent** [comment]
This is moved to https://github.com/NCAR/python-tutorial so should we close this issue?

**Comment by kmpaul** [comment]
Yeah.  Maybe we should reference this issue in the https://github.com/NCAR/python-tutorial issue and then close this.
