### ISSUE TITLE
Create Welcome.ipynb

### ISSUE THREAD

**Issue by jukent** [NCAR/ncar-python-tutorial#25]
Create a notebook that introduces Jupyter notebooks!

**Comment by andersy005** [comment]
@jukent, I moved things around. You may want to sync your local branch with the upstream branch if you haven't done so yet

**Comment by jukent** [comment]
I looked for that. Thanks for doing so!

**Comment by jukent** [comment]
So the concepts to show are:

What is a notebook file anyway?
Kernels
The dashboard
Cell blocks:
 - code
 - raw
 - markdown (and briefly to show that you can display equations, change font sizes, italics, bold, have an unexecutable code block inside of markdown, etc)


Does that order make sense?

**Comment by andersy005** [comment]
@jukent, sorry I didn't get to provide feedback for #27. I will take a look at it some time tomorrow and will see if I can anything to what you did in a PR.

**Comment by andersy005** [comment]
Let's keep this open for now

**Comment by jukent** [comment]
Yeah I realized the screenshots I was taking were from my local Jupyter deployment. I probably want to make sure they look exactly as they will on Cheyenne.

**Comment by andersy005** [comment]
Can you upload them inside a new `notebooks/assets` directory as part of #28 ? I would like to take a look at them
