### ISSUE TITLE
Notebook Template

### ISSUE THREAD

**Issue by andersy005** [NCAR/ncar-python-tutorial#29]
Could we adopt a template for notebooks in this repository? My proposition is to have:

- Table of contents section with links to different sections in the notebook itself
- A `learning objectives` section at the beginning of the notebook
- A `Going Further` section at the end of the notebook. This section could have references to documentation sections that are relevant to what was covered in the notebook and/or references to other notebooks. 

@kmpaul, @jukent any thoughts?

**Comment by matt-long** [comment]
Good idea. Unidata’s notebooks have something like this.

**Comment by jukent** [comment]
Yes this is a great idea Anderson. We also want to have consistent Markdown formatting.
