### ISSUE TITLE
ensure configure works with existing install

### ISSUE THREAD

**Issue by matt-long** [NCAR/ncar-python-tutorial#30]
Many people may already have Python setup. Is the configure script robust in this context?

**Comment by andersy005** [comment]
This is being handled by:


https://github.com/NCAR/ncar-python-tutorial/blob/0753eeee245f241664a8efd565965f36b5695ec0/setup/configure#L44
https://github.com/NCAR/ncar-python-tutorial/blob/0753eeee245f241664a8efd565965f36b5695ec0/setup/configure#L55-L60

https://github.com/NCAR/ncar-python-tutorial/blob/0753eeee245f241664a8efd565965f36b5695ec0/setup/configure#L80-L85


When a `conda` installation is available, we proceed to updating the `analysis` environment if it exists, if it doesn't, we create it. 

I tested this on my laptop yesterday. I will test it on Cheyenne as well.

**Comment by andersy005** [comment]
Addressed in #59, and other previous PRs.
