### ISSUE TITLE
Configure script doesn't work on clean Mac

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#41]
I have the perfect laptop to test this configure script with!  It's brand new with nothing on it!

Currently, with no `python3` installed, I get an error when trying to run the script.

**Comment by kmpaul** [comment]
Default installs of python on even the newest Macs are python 2.7.

**Comment by kmpaul** [comment]
I like the idea of portability.  Most systems have some version of python installed, but we need to make this script support python 2 and 3.

**Comment by andersy005** [comment]
> Default installs of python on even the newest Macs are python 2.7.

It's such a shame @ Apple 😀

I was well aware of this fact, but I still chose to take a shortcut by making the script Python 3 compatible only :) 

> Most systems have some version of python installed, but we need to make this script support python 2 and 3.

I concur

**Comment by kmpaul** [comment]
Also, Macs don't ship with `wget` (only `curl`) which is used (by default) to download the Miniconda installer

**Comment by kmpaul** [comment]
We also need to update the CircleCI scripts to _not_ use a base python3 container.  Rather, to use a base container that represents the default environment of someone who hasn't installed anything.

And we should create build jobs for linux (SUSE linux to mimic Cheyenne) and Mac and Windows.

**Comment by kmpaul** [comment]
BTW, I'm working on an update for Mac OS.  I'll submit a PR shortly.

**Comment by andersy005** [comment]
> And we should create build jobs for linux (SUSE linux to mimic Cheyenne) and Mac and Windows.

I am afraid we won't be able to test it on Mac on Windows via CircleCI. Per CircleCI documentation, you need to have a subscription to a **paid** plan: https://circleci.com/docs/2.0/hello-world-macos/#prerequisites

**Comment by kmpaul** [comment]
Ah.  I was afraid of that.

**Comment by andersy005** [comment]
> And we should create build jobs for linux (SUSE linux to mimic Cheyenne)

Since conda is OS-agnostic, and all we need is wget, and python3 from the system, do we need to do this?

**Comment by andersy005** [comment]
Are there any functionality that is SUSE linux specific that we should be testing against?

**Comment by kmpaul** [comment]
...Well, conda is _supposed_ to be OS-agnostic.  Can we trust that it actually is?

As for SLES specific functionality, I don't know.  Maybe not, and we can test with the same linux docker image but with different login shells.

**Comment by kmpaul** [comment]
We could move to Travis which now supports both MacOS and Windows.

**Comment by andersy005** [comment]
> Can we trust that it actually is?

Yes, we can :) 


> same linux docker image but with different login shells.

Testing against different login shells (bash, tcsh) seems crucial. 


Regarding Windows support, looking back at our last hackathon in June, I didn't see any single windows user. Should we focus on getting this to work on windows at the moment?

**Comment by andersy005** [comment]
Supporting windows would be worth the effort when there's actual demand IMHO :)

**Comment by kmpaul** [comment]
We had Windows users at the ACOM Python tutorial, but I haven't seen any since.

**Comment by kmpaul** [comment]
And, frankly, the word could be spreading from early Windows users that if you have a Windows machine, it's not worth it.  I'd like to make sure that isn't an issue.
