### ISSUE TITLE
Looking for plotting talks from last tutorial.

### ISSUE THREAD

**Issue by jukent** [NCAR/ncar-python-tutorial#48]
I found the advanced Xarray plotting tutorial -- archive/old-contents/notebooks/xarray/02-xarray-advanced-plotting.ipynb

but wasn't there a talk on Cartopy and data visualization in general? Is that stored in a different repo?

**Comment by andersy005** [comment]
@jukent, 

> Is that stored in a different repo?

Yes

https://github.com/ncar-hackathons/hands-on-examples/tree/master/visualization

**Comment by jukent** [comment]
Nice quick answers.

I think I'll keep these as 4 separate notebooks (Xarray, Cartopy, Matplotlib, and Holoviews) that link to one another. But I will go in and edit them.

**Comment by andersy005** [comment]
Closing this for now... Feel free to re-open it.
