### ISSUE TITLE
Check for `analysis` environment conflict

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#52]
Need to check if there already exists an `analysis` conda environment.  If it already exists, stop execution and tell the user to either (1) rename the environment or (2) remove the environment, and tell them the commands to do so.

Then they have to rerun the configure script.

**Comment by matt-long** [comment]
Rather than require the user to rename their environment, can we just rename ours?

**Comment by andersy005** [comment]
For simplicity, I renamed the analysis env from `analysis` --> `analysis-env`

**Comment by kmpaul** [comment]
This won’t solve the problem if this repo gets used again in the future.

**Comment by kmpaul** [comment]
There will always be name conflicts if we reuse this repo. So, I don’t think we should rename the environmental.

**Comment by andersy005** [comment]
I am not sure what would be the right long-term solution for this issue (given that this repo might be used in the future).

If the consensus is to keep the current setup as is, feel free to close #59

**Comment by kmpaul** [comment]
I think the issue is that @matt-long uses his analysis env regularly, and therefore doesn’t want to have to rename it or delete it. He’s probably not the only one after the June tutorial. 

So, I recommend that we choose a name that nobody would ever create for their own work. Like “python-tutorial”, **and** we implement the env name conflict check that we talked about for this issue. 

And we provide instructions to participants at the end of the tutorial on how to rename there env to something they would prefer for the long term.

**Comment by andersy005** [comment]
Here's what I have in #59 

```bash
$ ./setup/configure 
*** Found an existing Conda installation in: /Users/abanihi/opt/miniconda3/condabin/conda
*** (13:15:31) Step 1/6: Skipping Conda installation
*** (13:15:31) Step 2/6: Updating `base` environment
*** (13:16:20) Step 3/6: Checking for environment name conflict


Unable to proceed to next steps because of an existing `python-tutorial` environment and clobber is set to False

To address this issue, please try one of the following options:

(1)Create clone environment, and then remove original one:

    conda create --name new_name --clone python-tutorial

    conda remove --name python-tutorial

Or

(2)you can run the configure script with clobber set to True:

    ./setup/configure --clobber
```

**Comment by kmpaul** [comment]
This looks great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
