### ISSUE TITLE
Write dask lecture material

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#53]
Content should include:

- NCAR & Dask jobqueue
- Dask array
- Adaptive scaling
- Dashboard (on laptop and Cheyenne)
- Xarray chunking best practices and rechunking
- Possibly: map_blocks and map_overlap

**Comment by andersy005** [comment]
@kmpaul 

As I prepare to work on this, I am feeling decision paralysis creep in :). I am having a hard time deciding how to organizing all these Dask concepts in a way that doesn't confuse the user by jumping from one to another. My current plan is to have notebooks that are concise and limited to one or two topics, such that a reader can get through the example within a few minutes of reading.

Do you have any suggestions? :) 

Ccing @matt-long

**Comment by kmpaul** [comment]
In terms of organizing, I would present subtopics in the order that people will actually encounter them in a typical workflow. In other words, consider one of the parallel workflows from the first day and talk about each Dask subtopic in the order that they might see them in that workflow. 

Does that help?

**Comment by andersy005** [comment]
Yes, it does. Thank you!
