### ISSUE TITLE
Tutorial Data

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#54]
- [x] Need to identify the data needed for this tutorial.
- [x] Find a public place to host data so everyone can download it
- [x] Need to provide a script to download the data to other machine
- [x] Enable the configure script to automatically download data (if not on Cheyenne or Casper)
- [x] If on Cheyenne or Casper, provide soft-links to data

**Comment by jukent** [comment]
This is the parent directory of the data -- /glade/collections/cmip/CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r1i1p1f1/Omon/thetao/gn/v20180827

I will take some time this afternoon to dig through the subdirectories to the data used.

**Comment by andersy005** [comment]
@jukent, do we need all the 20 years worth of data or can we get a subset from this file?

**Comment by andersy005** [comment]
FYI:

`figshare` offers 20GB of free storage for account owners.  I am planning on hosting sample data (for users without an account on Cheyenne) under my figshare account if there are no objections

**Comment by jukent** [comment]
We can subset it, but we're not nearing that 20GB limit - so is it something we should do anyway?

**Comment by kmpaul** [comment]
What download speeds can we expect from figshare?

**Comment by matt-long** [comment]
why not use the CGD ftp location we had setup for exactly this thing?

**Comment by kmpaul** [comment]
Does the CGD ftp server allow anonymous download?  Who has permissions to upload?

**Comment by andersy005** [comment]
> why not use the CGD ftp location we had setup for exactly this thing?

@matt-long, I've not looked into this yet. I will give it a try before exploring the figshare option

> Does the CGD ftp server allow anonymous download? Who has permissions to upload?

@kmpaul, this needs further exploration


I am going to looking into the CGD's ftp server option this afternoon, and I will let you know how this goes

**Comment by andersy005** [comment]
@kmpaul 

> Does the CGD ftp server allow anonymous download? 

Yes. As a smoke test you can try downloading this script: 

`wget ftp://ftp.cgd.ucar.edu/archive/aletheia-data/test.sh`

> Who has permissions to upload?

As far as I know, Matt and I are among users with upload permissions.

**Comment by andersy005** [comment]
@matt-long,

I just figured  the FTP details out, and I am in favor of using the ftp server for sample data instead of figshare.

**Comment by matt-long** [comment]
Good. Regarding @kmpaul question.
> Who has permissions to upload?
Ultimately, I think we want to setup some sort of version control and have a means of getting input from other groups, but include a gate-keeper. I don't know what the best solutions in this regard are.

**Comment by kmpaul** [comment]
I think a small ftp service with versioned files might be something Jeff DLB’s division should provide.  They do this on a regular basis for  things like the RDA.

**Comment by jukent** [comment]
I limited the data to 5 years, it is now > 600 MB,
The path on Cheyenne is:
/glade/u/home/jkent/tutorial_data/thetao_Omon_historical_GISS-E2-1-G_r1i1p1f1_gn_185001-185512.nc
