### ISSUE TITLE
Alternate text for OHC Notebook 1

### ISSUE THREAD

**Issue by bonnland** [NCAR/ncar-python-tutorial#58]
import xarray as xr

Did that work for you? If not, you do not have xarray installed in your current notebook environment. Check to make sure it reads "Python [conda env: analysis]"  in the top right corner of your jupyter notebook screen.  If it just says "Python" or something else, then click on the text to change the selection, so that your "analysis" environment is used.

**Comment by andersy005** [comment]
Addressed in #60
