### ISSUE TITLE
Support self-guided as well as in-person tutorials

### ISSUE THREAD

**Issue by matt-long** [NCAR/ncar-python-tutorial#90]
It would be nice if we can point people to this repo to enable self-guided instruction. I think we have a pretty solid draft of the content we might like. 

Can we add a sphinx docs assembly of (some of) the notebooks into a sensible outline?

Considerations: 
- I think we'd like to include NCAR-specific material, but clearly delineate it as such.

- Some of the "workflow" notebooks are more pedagogical than others: we might consider reorganizing. The OHC example, for instance, provides a nice introductory, idealized example, whereas the O2 trends is really an "advanced example." In this sense, the OHC example belongs in Chapter 1, whereas the O2 trends notebook should be in an appendix.

**Comment by kmpaul** [comment]
We should also remove event-specific information from this repo, obviously.

**Comment by kmpaul** [comment]
https://drive.google.com/open?id=10Xk5f3c27BSGNftGXao5bnQMvF5WxZ3yEkmz9MTF1T4
