### ISSUE TITLE
Update Pangeo kernel on JHub and use for tutorial

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#94]
Need the Pangeo environment/kernel on the JHub updated to include all of the packages that we need for this tutorial.

Also need to tailor this tutorial for this new kernel.

**Comment by andersy005** [comment]
https://github.com/NCAR/hpc-jupyter-kernels/pull/11

**Comment by kmpaul** [comment]
Is this done?  Can we close this issue?

**Comment by andersy005** [comment]
> Is this done? 

Pinging @jbaksta
