### ISSUE TITLE
Update ssh tunnel scripts with option to select a default environment to use

### ISSUE THREAD

**Issue by andersy005** [NCAR/ncar-python-tutorial#96]
Currently, the ssh tunnel scripts in `scripts/jlab` require activating a conda environment with `jupyter` installed in it prior launching `./scripts/jlab/jlab-machine-name` script. We can improve the user experience by embedding this into the scripts themselves. One solution is to add an option for `conda_env_name` to activate prior launching the jupyter server, and adding a `conda activate $conda_env_name` step in the scripts themselves.

**Comment by matt-long** [comment]
I had this in a previous version of the scripts, but took it out once deciding that these scripts should launch from the conda base environment. I don't have to do `conda activate` before running the script, so I am somewhat skeptical of your assertion that that is necessary.

**Comment by mnlevy1981** [comment]
This is tied to #92, right? If we don't want users to change `(base)` then this functionality is needed.

@andersy005 I'm a little confused about how you worded the issue, though:

> the ssh tunnel scripts in `scripts/jlab` require activating a conda environment with `jupyter` installed in it prior launching `./scripts/jlab/jlab-machine-name` script"

seems to imply you need to have access to `jupyter` locally. That's not true, is it? You need to launch `jupyter lab` on the remote machine in an environment with `jupyter` (and, as @matt-long points out, currently the `base` environment fits the bill but that might change in the future)

**Comment by kmpaul** [comment]
Also, whether or not `base` is activated depends on how the user has set up conda.  For example, I have some old Python work that requires that I use the system-wide Python packages for the code to remain consistent.  In order to prevent my conda install on Cheyenne from interfering with system packages, I have to disable autoactivation of the `base` environment:

```bash
conda config --set auto_activate_base false
```

**Comment by kmpaul** [comment]
...so, if it wasn't obvious from what I said, that means that I need to `conda activate base` before doing anything.

**Comment by kmpaul** [comment]
It seems to me that the best solution to accommodate everyone is to have the `conda_env_name` default to `base`.

**Comment by kmpaul** [comment]
@mnlevy1981 You are correct that you need `jupyter lab` in the _remote_ machine's conda environment.   But I actually think that was what @andersy005 meant.  I think @andersy005 actually meant that you need to have `jupyter` installed in the remote environment _before_ you run the `jlab-machine` script on your local machine.

**Comment by andersy005** [comment]
Closing this as it's being handled in https://github.com/NCAR/jupyter-forward
