### ISSUE TITLE
Pull SSH launch scripts into separate package

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ncar-python-tutorial#98]
Currently, the `jlab-machine` launch scripts (using SSH tunneling) ship with the Python tutorial content.  However, these scripts are separately useful outside of the tutorial.  I believe that these launch scripts should be a stand-alone package that is a dependency for the tutorial.

First, I think that we should pull the launch scripts out into a separate repo and then make this repo installable via `pip`.  I don't think a conda install is required.  We will need a good name for this package.

Second, how we specify the launch-script package _as a dependency_ for the tutorial can be done in a couple of different ways:

1. We can make the tutorial a `pip` installable package, too, and explicitly declare the launch-scripts package as a dependency.
2. We can leave the tutorial content just as a repo and we can specify the launch-scripts package as a dependency in a the tutorial's conda environment file.

Option (2) is the easiest and perhaps the first step to take, regardless.

**Comment by jukent** [comment]
Not relevant for beginner tutorial.

**Comment by kmpaul** [comment]
Look at paramiko for ssh usage in a portable way

**Comment by mnlevy1981** [comment]
I have scripts sitting in https://github.com/NCAR/pangeo/tree/casper-support/client-side but they are extremely fragile.

1. they don't seem to work for users who rely on `csh` as their default shell
2. some users with `bash` as default shell have reported issues

**Comment by andersy005** [comment]
FYI, I started working on this in https://github.com/NCAR/jupyter-forward. Looking for collaborators ;)

**Comment by kmpaul** [comment]
Closing this issue with the creation of https://github.com/NCAR/jupyter-forward
